### ISSUE TITLE
Error al ejecutar testsys

### ISSUE THREAD

**Issue by adriantroconis** [gecos-team/gecosws-installation-disk-generator#1]
IOError: [Errno 13] Permission denied: '/var/gensys/testsys/gv9master/twistd.log'
./testsys/start: línea 10: buildslave: no se encontró la orden
./testsys/start: línea 11: buildslave: no se encontró la orden

Ésta es la salida de la cónsola al ejecutar, al parecer no se copió el buildslave...

Otra pregunta, si quiero hacer una build basada en otra distro? por ejemplo debian testing? Con un DE personalizado, otras features que se le añadan? Cómo se haría?

**Comment by alfem** [comment]
El owner de esos logs debería ser el usuario _gensys_. Si no es así, algo has hecho mal. Repasa las instrucciones de la wiki.

_Buildslave_ viene en el paquete buildbot, que deberías haber instalado previamente (ver de nuevo el wiki).

Hacer un curso completo sobre creación de distros sería interesante pero requiere un tiempo que no tenemos. Por supuesto es posible generar distribuciones basadas en _testing_, cambiando los repositorios de origen en la un par de sitios (https://github.com/gecos-team/gecosws-installation-disk-generator/tree/master/config/var/gensys/live-build/gecosv2-14.04/config/package-lists), pero es muy probable que al principio se rompan algunas cosas y necesites buenos conocimientos de BuildBot y Live-Build para arreglarlas (como de nuevo dice el wiki).

NOTA: En el futuro, te recomendamos que escribas un sólo tema por cada Issue. Y a ser posible en inglés (para que sea más fácil que lo lea y responda la comunidad a nivel mundial).

**Comment by adriantroconis** [comment]
Ok, Thanks for response friend... We are Venezuelan team that's interesting on gecos

**Comment by alfem** [comment]
Amateur, Pros, Goverment related? (If I can ask)

**Comment by adriantroconis** [comment]
A company interested on deploy this system with clients, check out our site www.quantic.com.ve (not finished yet) if you want can write me by email soporte@quantic.com.ve

**Comment by alfem** [comment]
Thanks! Mail sent.
